$schema = "https://railway.app/railway.schema.json"

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "postgres"
restartPolicyType = "UNLESS_STOPPED"
restartPolicyMaxRetries = 10