[deploy]
image = "postgres:14.19-bookworm"
startCommand = "postgres"
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10

[variables]
POSTGRES_HOST_AUTH_METHOD = "trust"
POSTGRES_USER = "postgres"
POSTGRES_DB = "sentry"